markdown: rdiscount
permalink: /:title/
url: http://hewen.github.io
name: hewen.github.io 
author: HeWen
email: HeWen.coder@gmail.com 
github: hewen
highlighter: pygments
safe: true
paginate: 5
truncate: 200
about: "<ul><li>PHPer</li>
        <li>Linux业余爱好者</li>
        <li>vim/emacs预备党员</li></ul>"
