markdown: rdiscount
permalink: /:title/
url: http://ehewen.org
name: HEWEN's blog
author: HeWen
email: wen.bin.he@foxmail.com
github: hewen
highlighter: pygments
safe: true
paginate: 6
truncate: 200
about: "<ul><li>PHPer</li>
        <li>Linux业余爱好者</li>
        <li>vim/emacs预备党员</li></ul>"
